import fs from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
const root=process.cwd(),evidence=path.join(root,'evidence/cinematic-product-world'),concepts=path.join(root,'site/concepts');
await fs.mkdir(path.join(concepts,'captures'),{recursive:true});
for(const file of (await fs.readdir(evidence)).filter(f=>/^study-.*\.png$/.test(f)))await sharp(path.join(evidence,file)).resize({width:1440,withoutEnlargement:true}).webp({quality:88}).toFile(path.join(concepts,'captures',file.replace('.png','.webp')));
const tests=JSON.parse(await fs.readFile(path.join(evidence,'browser-results.json'),'utf8'));
const perf=JSON.parse(await fs.readFile(path.join(evidence,'performance.json'),'utf8'));
let required;try{required=JSON.parse(await fs.readFile(path.join(evidence,'required-results.json'),'utf8'));}catch{required={status:'Repository checks are still running; see the final report.'};}
const maxLcp=Math.max(...perf.runs.map(r=>r.lcp)),maxCls=Math.max(...perf.runs.map(r=>r.cls));
const rows=[['copper','Copper Core','Recommended','Strongest balance of a memorable sculpture and a clear product story. Brushed copper, dark graphite and warm ivory.','Five beveled layers open as the hero leaves view; HTML tool fragments assemble into one workspace.'],['ivory','Ivory Architecture','Calmest','Architectural daylight and large serif typography. The quietest visual system, with the brightest workspace reveal.','Three pale layers give the object a monumental silhouette. Native scroll connects the object and workspace.'],['signal','Signal Chamber','Most atmospheric','A dark chamber of fine copper paths and a wireframe V. More technical in tone, with the same readable HTML controls.','Filaments converge around five wireframe layers. The mobile composition keeps the headline separate from the object.']];
let body=`<p class="eyebrow">RENDERED EVIDENCE / VARIATION 01</p><h1>Three directions.<br>Ready to compare.</h1><p class="gallery-intro">These are browser captures of working code. The separate reference gallery contains the generated art direction images. Copper Core is the complete website; Ivory and Signal are preserved hero and workspace motion studies.</p><a class="button primary" href="../index.html">Open complete Copper Core ↗</a> <a class="button secondary" href="index.html">View the visual references ↗</a>`;
for(const [key,name,verdict,composition,motion]of rows){body+=`<article class="concept-entry"><div class="concept-heading"><h2>${name}</h2><p>${verdict} · ${composition}</p><a class="button primary" href="${key}/index.html">Try the motion study ↗</a></div><p>${motion}</p><div class="reference-grid">`;for(const [suffix,label]of [['1440','Desktop hero'],['390','Mobile hero'],['1440-reveal','Desktop workspace reveal']])body+=`<figure><a href="captures/study-${key}-${suffix}.webp"><img loading="lazy" src="captures/study-${key}-${suffix}.webp" alt="${name}: ${label}" width="${suffix==='390'?390:1440}"></a><figcaption>${label} · Chromium capture</figcaption></figure>`;body+=`</div><p><a class="text-button" href="captures/study-${key}-390-reveal.webp">Inspect the mobile workspace capture ↗</a></p></article>`;}
body+=`<section class="comparison-notes"><h2>Verification and restoration</h2><p>Browser checks: ${tests.filter(t=>t.pass).length}/${tests.length}. The full page is checked at 360, 390, 768, 1280 × 720 and 1440 pixels, with keyboard, touch, reverse scrolling, browser back, microphone denial, late permission, unavailable WebGL, missing assets and no JavaScript.</p><p>Three cold-cache laptop runs: LCP up to ${(maxLcp/1000).toFixed(2)} seconds; CLS up to ${maxCls.toFixed(4)}. ${perf.conditions}</p><p>Software WebGL: median frame interval ${perf.smooth.medianInterval.toFixed(1)} ms; 95th percentile ${perf.smooth.p95Interval.toFixed(1)} ms. Hardware-accelerated devices use a higher rendering resolution. This measurement is not a claim of 60 fps on every device.</p><p>Repository checks: ${Object.entries(required).map(([k,v])=>`${k}: ${v===0?'passed':typeof v==='number'?'see report (exit '+v+')':v}`).join('; ')}.</p><p>Baseline source: <code>d08c7340e27cb3af509db4a9c81bfb2d1b6aaba2</code>. Reference milestone: <code>46153ea</code>. Complete implementation milestone: <code>77374b3</code>. Branch: <code>codex/cinematic-product-world-20260907</code>.</p><p>To inspect any prior version without touching another checkout, create a new detached worktree at its commit. The evidence README in the draft PR records the exact commands and test limitations. No production publication was performed.</p></section>`;
await fs.writeFile(path.join(concepts,'review.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>VibeSpace — comparison evidence</title><link rel="stylesheet" href="../css/cinematic.css"></head><body class="concept-gallery"><a class="skip-link" href="#main-content">Skip to content</a><header class="gallery-nav"><a class="wordmark" href="../index.html">VibeSpace</a><a href="index.html">Three visual directions ↗</a></header><main id="main-content" class="section-pad">${body}</main></body></html>`);
console.log('Comparison evidence generated.');
