export interface TerminalTextLimits {
  maxBytes: number;
  maxLines: number;
  truncationMarker?: string;
}

export interface SanitizedTerminalText {
  text: string;
  truncated: boolean;
}

const DEFAULT_TRUNCATION_MARKER = '[...terminal output trimmed...]\n';
const MAX_PERSISTED_DRAFT_BYTES = 4 * 1024;
const encoder = new TextEncoder();

// Terminal protocol emitted by a PTY or generated by xterm input handling.
const OSC_SEQUENCE = /\x1B\][\s\S]*?(?:\x07|\x1B\\)/g;
const UNTERMINATED_OSC = /\x1B\][^\r\n]*/g;
const DCS_SEQUENCE = /\x1BP[\s\S]*?\x1B\\/g;
const UNTERMINATED_DCS = /\x1BP[^\r\n]*/g;
const CSI_SEQUENCE = /\x1B\[[\x30-\x3F]*[\x20-\x2F]*[\x40-\x7E]/g;
const SS3_SEQUENCE = /\x1BO./g;
const SIMPLE_ESCAPE = /\x1B./g;
const ORPHAN_MOUSE_REPORT = /(?:\[<|<)\d{1,3};\d{1,5};\d{1,5}[Mm]/g;
const ORPHAN_PALETTE = /(^|[\r\n])\](?:4|10|11|12);[^\r\n\x07]*/g;
const ORPHAN_FOCUS = /\[(?:I|O)(?=$|[^A-Za-z0-9_])/g;
const ORPHAN_CSI = /\[(?:\??\d[\d;?]*|[;?][\d;?]*)[\x20-\x2F]*[A-Za-z]/g;
// Keep tab/newline/carriage return until line normalization.
// eslint-disable-next-line no-control-regex
const C0_C1_CONTROLS = /[\x00-\x08\x0B\x0C\x0E-\x1F\x7F-\x9F]/g;

const SENSITIVE_PROMPT =
  /(?:password|passphrase|(?:^|\W)pin|api[ _-]?key|access[ _-]?token|client[ _-]?secret|private[ _-]?key|credential)(?:\s+for\s+[^\r\n:]+)?\s*[:?>]\s*$/i;

function stripTerminalProtocol(input: string): string {
  return input
    .replace(OSC_SEQUENCE, '')
    .replace(UNTERMINATED_OSC, '')
    .replace(DCS_SEQUENCE, '')
    .replace(UNTERMINATED_DCS, '')
    .replace(CSI_SEQUENCE, '')
    .replace(SS3_SEQUENCE, '')
    .replace(SIMPLE_ESCAPE, '')
    .replace(ORPHAN_MOUSE_REPORT, '')
    .replace(ORPHAN_PALETTE, '$1')
    .replace(ORPHAN_FOCUS, '')
    .replace(ORPHAN_CSI, '')
    .replace(/\x1B/g, '')
    .replace(C0_C1_CONTROLS, '');
}

function redactLikelySecrets(input: string): string {
  return input
    .replace(
      /(\bAuthorization\s*:\s*(?:Bearer|Basic)\s+)[^\s]+/gi,
      '$1[REDACTED]',
    )
    .replace(
      /(\b[a-z][a-z0-9+.-]*:\/\/[^:\s/@]+:)[^@\s/]+(@)/gi,
      '$1[REDACTED]$2',
    )
    .replace(
      /(\b[A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD|CREDENTIAL)[A-Z0-9_]*\s*[:=]\s*)(?:"[^"]*"|'[^']*'|[^\s]+)/gi,
      '$1[REDACTED]',
    )
    .replace(
      /\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b/g,
      '[REDACTED JWT]',
    )
    .replace(
      /\b(?:sk-(?:live|test|proj)-|rk_live_|gh[pousr]_|github_pat_|xox[baprs]-|sbp_)[A-Za-z0-9_-]{10,}\b/g,
      '[REDACTED TOKEN]',
    )
    .replace(/\bAKIA[A-Z0-9]{12,}\b/g, '[REDACTED AWS ACCESS KEY]');
}

function utf8ByteLength(value: string): number {
  return encoder.encode(value).byteLength;
}

function utf8Tail(value: string, maxBytes: number): string {
  if (maxBytes <= 0) return '';
  if (utf8ByteLength(value) <= maxBytes) return value;

  const codePoints = Array.from(value);
  let bytes = 0;
  let start = codePoints.length;
  while (start > 0) {
    const nextBytes = utf8ByteLength(codePoints[start - 1] ?? '');
    if (bytes + nextBytes > maxBytes) break;
    bytes += nextBytes;
    start -= 1;
  }
  return codePoints.slice(start).join('');
}

function boundedTail(
  input: string,
  limits: TerminalTextLimits,
): SanitizedTerminalText {
  const maxBytes = Math.max(0, Math.floor(limits.maxBytes));
  const maxLines = Math.max(0, Math.floor(limits.maxLines));
  const marker = limits.truncationMarker ?? DEFAULT_TRUNCATION_MARKER;
  if (maxBytes === 0 || maxLines === 0 || !input) {
    return { text: '', truncated: Boolean(input) };
  }

  const sourceLines = input.split('\n');
  let truncated = sourceLines.length > maxLines;
  const dataLineBudget =
    truncated && marker ? Math.max(1, maxLines - 1) : maxLines;
  let lines = sourceLines.slice(-dataLineBudget);
  let body = lines.join('\n');

  if (utf8ByteLength(body) > maxBytes) truncated = true;
  const prefix = truncated ? utf8Tail(marker, maxBytes) : '';
  const bodyBudget = Math.max(0, maxBytes - utf8ByteLength(prefix));

  if (truncated && marker && lines.length > Math.max(1, maxLines - 1)) {
    lines = lines.slice(-Math.max(1, maxLines - 1));
    body = lines.join('\n');
  }

  let bodyBytes = utf8ByteLength(body);
  let lineHead = 0;
  while (lines.length - lineHead > 1 && bodyBytes > bodyBudget) {
    bodyBytes -= utf8ByteLength(lines[lineHead] ?? '') + 1;
    lineHead += 1;
  }
  if (lineHead > 0) {
    lines = lines.slice(lineHead);
    body = lines.join('\n');
  }
  if (utf8ByteLength(body) > bodyBudget) {
    body = utf8Tail(body, bodyBudget);
  }

  return {
    text: `${prefix}${body}`,
    truncated,
  };
}

export function sanitizePersistedTerminalText(
  input: string,
  limits: TerminalTextLimits,
): SanitizedTerminalText {
  if (!input) return { text: '', truncated: false };
  const normalized = redactLikelySecrets(stripTerminalProtocol(input))
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n');
  return boundedTail(normalized, limits);
}

export function isSensitiveTerminalPrompt(recentOutput: string): boolean {
  if (!recentOutput) return false;
  const tail = stripTerminalProtocol(recentOutput).slice(-512);
  return SENSITIVE_PROMPT.test(tail);
}

export function sanitizePersistedDraft(
  input: string,
  recentOutput = '',
): string {
  if (!input || isSensitiveTerminalPrompt(recentOutput)) return '';
  const printable = redactLikelySecrets(stripTerminalProtocol(input))
    .replace(/[\r\n\t]/g, '');
  return utf8Tail(printable, MAX_PERSISTED_DRAFT_BYTES);
}
