import { Archive, Cpu } from 'lucide-react';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import type { LocalAdapterRecord } from './adapterRegistry';

export function RealAdapterRegistryPanel({ records, runtimeReady, onUse, onProbe, onEvaluate, onPromote, onArchive }: { records: readonly LocalAdapterRecord[]; runtimeReady: boolean; onUse: (record: LocalAdapterRecord) => void; onProbe: (record: LocalAdapterRecord) => void; onEvaluate: (record: LocalAdapterRecord) => void; onPromote: (record: LocalAdapterRecord) => void; onArchive: (record: LocalAdapterRecord) => void }) {
  if (!records.length) return null;
  return <Card className="border-emerald-500/25"><CardHeader><CardTitle className="flex items-center gap-2"><Cpu className="h-5 w-5 text-emerald-300" /> Local adapter registry</CardTitle><CardDescription>Evaluation is local and mandatory. Only a manually approved passing adapter can route chats.</CardDescription></CardHeader><CardContent className="space-y-3">{records.map((record) => { const evaluated = record.evaluation?.artifactManifestSha256 === record.artifactManifestSha256; const passing = evaluated && record.evaluation?.report.gate === 'pass'; return <div key={record.jobId} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><div className="font-mono text-metadata">{record.jobId} · {record.artifactManifestSha256.slice(0, 12)}…</div><div className="mt-1 text-metadata text-muted-foreground">{record.status === 'promoted' ? 'Champion' : record.status === 'archived' ? 'Archived' : !evaluated ? 'Needs evaluation' : passing ? `Passed: ${record.evaluation!.report.candidateScore.toFixed(3)} (${record.evaluation!.report.delta >= 0 ? '+' : ''}${record.evaluation!.report.delta.toFixed(3)} vs base)` : 'Blocked by evaluation gate'}</div></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={!runtimeReady || record.status === 'archived'} onClick={() => onProbe(record)}>Probe</Button><Button variant="outline" disabled={!runtimeReady || record.status === 'archived'} onClick={() => onEvaluate(record)}>Evaluate</Button><Button variant="accent" disabled={!passing || record.status === 'promoted'} onClick={() => onPromote(record)}>{record.status === 'promoted' ? 'Champion' : 'Approve & promote'}</Button><Button variant="accent" disabled={!runtimeReady || record.status !== 'promoted'} onClick={() => onUse(record)}>Use in chat</Button><Button variant="outline" aria-label={`Archive adapter ${record.jobId}`} onClick={() => onArchive(record)}><Archive className="h-4 w-4" /></Button></div></div>; })}</CardContent></Card>;
}
