import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT = fileURLToPath(new URL('..', import.meta.url));
const SITE = join(ROOT, 'site');
const OUT = join(ROOT, 'docs', 'screenshots', 'vibespace');
const MIME={'.html':'text/html','.js':'text/javascript','.mjs':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.woff':'font/woff','.woff2':'font/woff2','.ttf':'font/ttf','.webp':'image/webp'};
const server=createServer(async(req,res)=>{try{const u=decodeURIComponent((req.url||'/').split('?')[0]);let f=join(SITE,u==='/'?'index.html':u);if(!existsSync(f))f=join(SITE,'index.html');const d=await readFile(f);res.writeHead(200,{'Content-Type':MIME[extname(f)]||'application/octet-stream'});res.end(d);}catch{res.writeHead(404);res.end('x');}});
await new Promise(r=>server.listen(8943,r));
await mkdir(OUT,{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const ctx=await browser.newContext({viewport:{width:1440,height:900}});
const page=await ctx.newPage();
const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:8943/',{waitUntil:'networkidle'});
await page.waitForTimeout(2500);
await page.screenshot({path:join(OUT,'site-index.png')});
console.log('captured site-index.png consoleErrors='+errors.length);
if(errors.length)console.log('  '+errors[0].slice(0,180));
await browser.close();server.close();
